Model for MIN rural CVD

In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv("CVD_Data_ (1).csv")
dff=pd.read_excel("CVD_linearRegression.xlsx")

In [2]:
df.dropna()

,State,Year,Climate_Change_Disasters,Min_Temp,Max_Temp,Average_Temp,PM2.5,Health_Quotient,HDI,Rural_Poppulation,Min_Rural_CVD,Max_Rural_CVD,Urban_Poppulation,Min_Urban_CVD,Max_Urban_CVD
0,Andhra Pradesh,2015,2,22.33,31.42,26.88,28.6,57.75,0.627,3.395143e+07,541266.571,2503357.892,1.699610e+07,169960.964,2243484.725
1,Andhra Pradesh,2016,2,22.33,31.50,26.92,28.9,60.16,0.633,3.425798e+07,546153.572,2525960.268,1.714955e+07,171495.512,2263740.752
2,Andhra Pradesh,2017,1,23.25,31.67,27.46,31.9,65.13,0.644,3.456110e+07,550986.070,2548310.572,1.730129e+07,173012.945,2283770.875
3,Andhra Pradesh,2018,0,24.92,36.70,30.81,31.8,64.17,0.646,3.486079e+07,555763.819,2570407.663,1.745132e+07,174513.187,2303574.070
4,Andhra Pradesh,2019,1,24.00,32.50,28.25,29.0,68.88,0.649,3.515703e+07,560486.623,2592250.630,1.759962e+07,175996.176,2323149.522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Puducherry,2018,0,26.92,31.00,28.96,29.8,49.26,0.736,4.921597e+05,7874.555,36419.819,1.061865e+06,10618.653,140166.217
260,Puducherry,2019,0,26.75,30.75,28.75,27.5,46.54,0.740,5.065981e+05,8105.569,37488.257,1.093017e+06,10930.169,144278.235
261,Puducherry,2020,1,26.00,30.50,28.25,26.1,47.48,0.743,5.211628e+05,8338.605,38566.046,1.124441e+06,11244.412,148426.240
262,Puducherry,2021,1,25.33,30.75,28.04,28.7,44.76,0.748,5.358466e+05,8573.545,39652.647,1.156122e+06,11561.224,152608.159
263,Puducherry,2022,0,25.03,30.75,27.89,37.0,42.04,0.751,5.383900e+05,8614.240,39840.860,1.161610e+06,11616.100,153332.520

In [3]:
df['State'].unique()

array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
       'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal pradesh',
       'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh',
       'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland',
       'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Tripura', 'Uttarakhand', 'Uttar Pradesh',
       'West Bengal', 'Andaman & Nicobar islands', 'Chandigarh',
       'Dadra & Nagar Haveli & Daman & diu', 'Jammu & Kashmir',
       'Puducherry'], dtype=object)

In [4]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
import pandas as pd

# Split the data into training and test sets
X = df[[ 'Climate_Change_Disasters',
       'Min_Temp', 'Max_Temp', 'PM2.5', 'Health_Quotient',
       'HDI', 'Rural_Poppulation']]
y = df['Min_Rural_CVD']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train your model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Evaluate your model on the test data
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)

print('R^2 score:', r2)
mse = mean_squared_error(y_test, y_pred)

# Compute the number of independent variables in the model
n = X_test.shape[0]
p = X_test.shape[1]

# Compute the adjusted R-squared score
adjusted_r2 = 1 - ((1 - r2) * (n - 1)) / (n - p - 1)


print('Model R-squared score:', r2)
print('Model adjusted R-squared score:', adjusted_r2)

R^2 score: 0.9969492627315388
Model R-squared score: 0.9969492627315388
Model adjusted R-squared score: 0.9964747036008893

Prediction

In [5]:
dff.columns

Index(['State', 'Climate_Change_Disasters', 'Min_Temp', 'Max_Temp', 'PM2.5',
       'Health_Quotient', 'HDI', 'Rural_Poppulation', 'Urban_Poppulation'],
      dtype='object')

In [6]:
dff1=dff[[ 'Climate_Change_Disasters', 'Min_Temp', 'Max_Temp', 'PM2.5', 'Health_Quotient', 'HDI', 'Rural_Poppulation']]

In [7]:
model.predict(dff1)

array([5.83846812e+05, 5.92975887e+05, 6.02938340e+05, 2.24946067e+04,
       2.26766166e+04, 2.28187410e+04, 5.14485630e+05, 5.20578987e+05,
       5.45229823e+05, 1.96872505e+06, 2.02641126e+06, 2.12413858e+06,
       4.05013917e+05, 4.17749965e+05, 4.39343157e+05, 9.62048104e+03,
       9.63598880e+03, 9.70134712e+03, 6.70074089e+05, 6.80869031e+05,
       6.88674463e+05, 3.16131004e+05, 3.18553642e+05, 3.18542040e+05,
       1.09069445e+05, 1.09145910e+05, 1.09438420e+05, 5.00509083e+05,
       5.11140284e+05, 5.33980763e+05, 6.94827091e+05, 6.95694541e+05,
       6.96375988e+05, 2.96737459e+05, 2.97363467e+05, 2.97755254e+05,
       1.03091104e+06, 1.03809991e+06, 1.04721918e+06, 1.11097280e+06,
       1.11077800e+06, 1.11077800e+06, 4.12146772e+04, 4.25264782e+04,
       4.31545694e+04, 4.91990951e+04, 4.91652150e+04, 4.90464064e+04,
       1.01350784e+04, 1.01902290e+04, 1.01874584e+04, 2.27585305e+04,
       2.27844333e+04, 2.27980872e+04, 6.47143037e+05, 6.53561528e+05,
       6.58082872e+05, 3.19631146e+05, 3.20014164e+05, 3.20014164e+05,
       9.91766059e+05, 1.02353287e+06, 1.02703563e+06, 8.16100694e+03,
       8.21840284e+03, 8.27979102e+03, 6.98692089e+05, 6.98692089e+05,
       6.98893886e+05, 4.08910901e+05, 4.25603059e+05, 4.36993044e+05,
       5.00811948e+04, 4.93687124e+04, 4.81084224e+04, 1.27054154e+05,
       1.27170017e+05, 1.27378732e+05, 2.83168944e+06, 2.84229158e+06,
       2.83716134e+06, 1.16487629e+06, 1.16626494e+06, 1.16566908e+06,
       3.96836449e+03, 3.75688352e+03, 3.76311141e+03, 5.09476150e+02,
       5.09476150e+02, 9.17116060e+02, 3.41273701e+03, 3.38609931e+03,
       3.69105609e+03, 1.79434548e+05, 1.79230373e+05, 1.79302795e+05,
       9.25957686e+03, 9.29008886e+03, 9.50489651e+03])

In [8]:
arr = np.array([5.83846812e+05, 5.92975887e+05, 6.02938340e+05, 2.24946067e+04,
       2.26766166e+04, 2.28187410e+04, 5.14485630e+05, 5.20578987e+05,
       5.45229823e+05, 1.96872505e+06, 2.02641126e+06, 2.12413858e+06,
       4.05013917e+05, 4.17749965e+05, 4.39343157e+05, 9.62048104e+03,
       9.63598880e+03, 9.70134712e+03, 6.70074089e+05, 6.80869031e+05,
       6.88674463e+05, 3.16131004e+05, 3.18553642e+05, 3.18542040e+05,
       1.09069445e+05, 1.09145910e+05, 1.09438420e+05, 5.00509083e+05,
       5.11140284e+05, 5.33980763e+05, 6.94827091e+05, 6.95694541e+05,
       6.96375988e+05, 2.96737459e+05, 2.97363467e+05, 2.97755254e+05,
       1.03091104e+06, 1.03809991e+06, 1.04721918e+06, 1.11097280e+06,
       1.11077800e+06, 1.11077800e+06, 4.12146772e+04, 4.25264782e+04,
       4.31545694e+04, 4.91990951e+04, 4.91652150e+04, 4.90464064e+04,
       1.01350784e+04, 1.01902290e+04, 1.01874584e+04, 2.27585305e+04,
       2.27844333e+04, 2.27980872e+04, 6.47143037e+05, 6.53561528e+05,
       6.58082872e+05, 3.19631146e+05, 3.20014164e+05, 3.20014164e+05,
       9.91766059e+05, 1.02353287e+06, 1.02703563e+06, 8.16100694e+03,
       8.21840284e+03, 8.27979102e+03, 6.98692089e+05, 6.98692089e+05,
       6.98893886e+05, 4.08910901e+05, 4.25603059e+05, 4.36993044e+05,
       5.00811948e+04, 4.93687124e+04, 4.81084224e+04, 1.27054154e+05,
       1.27170017e+05, 1.27378732e+05, 2.83168944e+06, 2.84229158e+06,
       2.83716134e+06, 1.16487629e+06, 1.16626494e+06, 1.16566908e+06,
       3.96836449e+03, 3.75688352e+03, 3.76311141e+03, 5.09476150e+02,
       5.09476150e+02, 9.17116060e+02, 3.41273701e+03, 3.38609931e+03,
       3.69105609e+03, 1.79434548e+05, 1.79230373e+05, 1.79302795e+05,
       9.25957686e+03, 9.29008886e+03, 9.50489651e+03])

In [10]:
arr = np.round(arr, decimals=0)
arr = arr.astype(int)
arr

array([ 583846,  592975,  602938,   22494,   22676,   22818,  514485,
        520578,  545229, 1968725, 2026411, 2124138,  405013,  417749,
        439343,    9620,    9635,    9701,  670074,  680869,  688674,
        316131,  318553,  318542,  109069,  109145,  109438,  500509,
        511140,  533980,  694827,  695694,  696375,  296737,  297363,
        297755, 1030911, 1038099, 1047219, 1110972, 1110778, 1110778,
         41214,   42526,   43154,   49199,   49165,   49046,   10135,
         10190,   10187,   22758,   22784,   22798,  647143,  653561,
        658082,  319631,  320014,  320014,  991766, 1023532, 1027035,
          8161,    8218,    8279,  698692,  698692,  698893,  408910,
        425603,  436993,   50081,   49368,   48108,  127054,  127170,
        127378, 2831689, 2842291, 2837161, 1164876, 1166264, 1165669,
          3968,    3756,    3763,     509,     509,     917,    3412,
          3386,    3691,  179434,  179230,  179302,    9259,    9290,
          9504])